"""tg_username

Revision ID: b6ba0d651a0d
Revises: 33d7e12293d2
Create Date: 2026-04-16 10:35:48.564184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ba0d651a0d'
down_revision: Union[str, None] = '33d7e12293d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.String(), nullable=True))
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###
