name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Cloud.ru Container Registry
        run: |
          docker login tiir-registry.cr.cloud.ru \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend docker image to Cloud.ru registry
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            tiir-registry.cr.cloud.ru/backend-student-and-t:latest

      - name: Build and push frontend docker image to Cloud.ru registry
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            tiir-registry.cr.cloud.ru/frontend-student-and-t:latest

      - name: Install cloudlogin
        run: |
          curl -LO https://github.com/cloud-ru-tech/cloudlogin/releases/download/v1.0.2/cloudlogin_Linux_amd64.tar.gz
          tar -xzf cloudlogin_Linux_amd64.tar.gz
          sudo mv cloudlogin /usr/local/bin/

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy services
        run: |
          kubectl apply -f deploy/backend
          kubectl apply -f deploy/frontend
